project:
  type: website
  output-dir: docs

website:
  title: "bioinformer"
  site-url: https://www.myblogexample.io
  description: "A great sample blog"
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: litera
    css: styles.css



